# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:18.7
    steps:
      - checkout
      - run:
          name: NPM 0xweb
          command: npm install 0xweb@latest
      - run:
          name: 0xweb init
          command: npx 0xweb init
      - run:
          name: Install USDC
          command: npx 0xweb i 0xa2327a938febf5fec13bacfb16ae10ecbc4cbdcf --chain eth --name USDC
      - run:
          name: Run tests
          command: npm run test

workflows:
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # https://circleci.com/docs/2.0/configuration-reference/#workflows
  TestRunner:
    jobs:
      - build-and-test
